'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HDTVoice.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to attack.
        '''</summary>
        Friend ReadOnly Property ATTACKLONG() As String
            Get
                Return ResourceManager.GetString("ATTACKLONG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to go,attack.
        '''</summary>
        Friend ReadOnly Property ATTACKSHORT() As String
            Get
                Return ResourceManager.GetString("ATTACKSHORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to with,using.
        '''</summary>
        Friend ReadOnly Property ATTACKWITH() As String
            Get
                Return ResourceManager.GetString("ATTACKWITH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to cancel.
        '''</summary>
        Friend ReadOnly Property CANCELCLICK() As String
            Get
                Return ResourceManager.GetString("CANCELCLICK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to card.
        '''</summary>
        Friend ReadOnly Property CARD() As String
            Get
                Return ResourceManager.GetString("CARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to choose,pick,select.
        '''</summary>
        Friend ReadOnly Property CHOOSECOMMAND() As String
            Get
                Return ResourceManager.GetString("CHOOSECOMMAND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to of.
        '''</summary>
        Friend ReadOnly Property CHOOSEOF() As String
            Get
                Return ResourceManager.GetString("CHOOSEOF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to option,card.
        '''</summary>
        Friend ReadOnly Property CHOOSEOPTION() As String
            Get
                Return ResourceManager.GetString("CHOOSEOPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to click.
        '''</summary>
        Friend ReadOnly Property CLICK() As String
            Get
                Return ResourceManager.GetString("CLICK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to say,emote.
        '''</summary>
        Friend ReadOnly Property EMOTE() As String
            Get
                Return ResourceManager.GetString("EMOTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hello,greetings.
        '''</summary>
        Friend ReadOnly Property EMOTEGREETINGS() As String
            Get
                Return ResourceManager.GetString("EMOTEGREETINGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to oops.
        '''</summary>
        Friend ReadOnly Property EMOTEOOPS() As String
            Get
                Return ResourceManager.GetString("EMOTEOOPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sorry.
        '''</summary>
        Friend ReadOnly Property EMOTESORRY() As String
            Get
                Return ResourceManager.GetString("EMOTESORRY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to thanks,thank you.
        '''</summary>
        Friend ReadOnly Property EMOTETHANKS() As String
            Get
                Return ResourceManager.GetString("EMOTETHANKS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to threaten.
        '''</summary>
        Friend ReadOnly Property EMOTETHREATEN() As String
            Get
                Return ResourceManager.GetString("EMOTETHREATEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to well played.
        '''</summary>
        Friend ReadOnly Property EMOTEWELLPLAYED() As String
            Get
                Return ResourceManager.GetString("EMOTEWELLPLAYED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to end current turn.
        '''</summary>
        Friend ReadOnly Property ENDTURNLONG() As String
            Get
                Return ResourceManager.GetString("ENDTURNLONG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to end turn.
        '''</summary>
        Friend ReadOnly Property ENDTURNSHORT() As String
            Get
                Return ResourceManager.GetString("ENDTURNSHORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to my,friendly.
        '''</summary>
        Friend ReadOnly Property FRIENDLY() As String
            Get
                Return ResourceManager.GetString("FRIENDLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hero,face.
        '''</summary>
        Friend ReadOnly Property HERO() As String
            Get
                Return ResourceManager.GetString("HERO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hero power.
        '''</summary>
        Friend ReadOnly Property HEROPOWER() As String
            Get
                Return ResourceManager.GetString("HEROPOWER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minion.
        '''</summary>
        Friend ReadOnly Property MINION() As String
            Get
                Return ResourceManager.GetString("MINION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to click.
        '''</summary>
        Friend ReadOnly Property MULLIGANCLICK() As String
            Get
                Return ResourceManager.GetString("MULLIGANCLICK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to confirm.
        '''</summary>
        Friend ReadOnly Property MULLIGANCONFIRM() As String
            Get
                Return ResourceManager.GetString("MULLIGANCONFIRM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to enemy,opposing,opponent.
        '''</summary>
        Friend ReadOnly Property OPPOSING() As String
            Get
                Return ResourceManager.GetString("OPPOSING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to play.
        '''</summary>
        Friend ReadOnly Property PLAYCARD() As String
            Get
                Return ResourceManager.GetString("PLAYCARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to on.
        '''</summary>
        Friend ReadOnly Property PLAYON() As String
            Get
                Return ResourceManager.GetString("PLAYON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to to.
        '''</summary>
        Friend ReadOnly Property PLAYTO() As String
            Get
                Return ResourceManager.GetString("PLAYTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property sound() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to target.
        '''</summary>
        Friend ReadOnly Property TARGET() As String
            Get
                Return ResourceManager.GetString("TARGET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to use.
        '''</summary>
        Friend ReadOnly Property USEHEROPOWER() As String
            Get
                Return ResourceManager.GetString("USEHEROPOWER", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
